name: Build and Deploy to Azure Web App (Docker)

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # OPCIONAL: Cachear dependencias npm si usas npm install en el workflow o Docker
      - name: Cachear módulos de Node
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # OPCIONAL: Reintentar npm install si lo necesitas en algún paso previo
      # - name: Instalar dependencias con reintentos
      #   run: |
      #     for i in {1..3}; do
      #       npm install && break || sleep 10;
      #     done

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/examen-app:${{ github.sha }} .
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/examen-app:${{ github.sha }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          images: ${{ secrets.ACR_LOGIN_SERVER }}/examen-app:${{ github.sha }}
